name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: omnomchomsky/markup_engine
        path: ../
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
