name: Build and Run LeadSheet Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Add static file
        run: | 
          mv ./leadsheetml/.cargo/SuperCargo.toml Cargo.toml

      - name: Checkout Markup Engine
        uses: actions/checkout@v4
        with:
          repository: omnomchomsky/markup_engine
          path: ./markup_engine

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
